import type { Elev, Bokningsgrad, Bokning } from '../types/optima';

/** Mock pupils, standing in for a real API/CMS response while prototyping. */
export const elever: Elev[] = [
	{
		id: 'johanna-johansson',
		namn: 'Johanna Johansson',
		personnummer: '19900420-1234',
		mobil: '+46 (0)73 123 45 67',
		epost: 'johanna.johansson@domain.se',
		adress: 'Nångatan 123',
		postnummer: '12345',
		ort: 'Platsstad',
		behorighet: ['AM', 'B'],
		registrerad: '2026-05-27',
		status: 'Aktiv',
		saldo: 4300.5,
		lektionssaldo: 0,
		skapad: '2026-05-27 av Admin Adminsson',
		senastAndrad: '2026-08-10 av Anders Andersson',
		vardnadshavare: 'Bengt Johansson',
	},
	{
		id: 'anders-andersson',
		namn: 'Anders Andersson',
		personnummer: '123456-1234',
		mobil: '072-1234567',
		epost: 'anders.andersson@domain.se',
		adress: 'Storgatan 1',
		postnummer: '12345',
		ort: 'Platsstad',
		behorighet: ['B'],
		registrerad: '2026-08-10',
		status: 'Aktiv',
		saldo: 1200,
		lektionssaldo: 3,
		skapad: '2026-08-10 av Admin Adminsson',
		senastAndrad: '2026-08-10 av Admin Adminsson',
	},
	{
		id: 'bengt-bengtsson',
		namn: 'Bengt Bengtsson',
		personnummer: '223456-1234',
		mobil: '072-1234567',
		epost: 'bengt.bengtsson@domain.se',
		adress: 'Lillgatan 4',
		postnummer: '12345',
		ort: 'Platsstad',
		behorighet: ['AM'],
		registrerad: '2026-08-09',
		status: 'Aktiv',
		saldo: 800,
		lektionssaldo: 1,
		skapad: '2026-08-09 av Admin Adminsson',
		senastAndrad: '2026-08-09 av Admin Adminsson',
	},
	{
		id: 'cecilia-clausen',
		namn: 'Cecilia Clausen',
		personnummer: '343456-1234',
		mobil: '070-1234567',
		epost: 'cecilia.clausen@domain.se',
		adress: 'Kungsvägen 8',
		postnummer: '12345',
		ort: 'Platsstad',
		behorighet: ['AM', 'B'],
		registrerad: '2026-08-06',
		status: 'Väntar',
		saldo: 0,
		lektionssaldo: 0,
		skapad: '2026-08-06 av Admin Adminsson',
		senastAndrad: '2026-08-06 av Admin Adminsson',
	},
	{
		id: 'stella-eriksdatter',
		namn: 'Stella Eriksdatter',
		personnummer: '111111-1234',
		mobil: '073-1234567',
		epost: 'stella.eriksdatter@domain.se',
		adress: 'Backvägen 2',
		postnummer: '12345',
		ort: 'Platsstad',
		behorighet: ['B'],
		registrerad: '2026-08-05',
		status: 'Aktiv',
		saldo: 2400,
		lektionssaldo: 2,
		skapad: '2026-08-05 av Admin Adminsson',
		senastAndrad: '2026-08-05 av Admin Adminsson',
	},
	{
		id: 'jens-eriksson',
		namn: 'Jens Eriksson',
		personnummer: '444444-1234',
		mobil: '073-1234567',
		epost: 'jens.eriksson@domain.se',
		adress: 'Skolgatan 9',
		postnummer: '12345',
		ort: 'Platsstad',
		behorighet: ['B'],
		registrerad: '2026-08-04',
		status: 'Inaktiv',
		saldo: 0,
		lektionssaldo: 0,
		skapad: '2026-08-04 av Admin Adminsson',
		senastAndrad: '2026-08-04 av Admin Adminsson',
	},
];

/** Booking rate per weekday, feeding the dashboard's bar chart. */
export const bokningsgrad: Bokningsgrad[] = [
	{ dag: 'Tor', datum: '13 aug', procent: 50 },
	{ dag: 'Fre', datum: '13 aug', procent: 100 },
	{ dag: 'Lör', datum: '13 aug', procent: 80 },
	{ dag: 'Sön', datum: '13 aug', procent: 50 },
	{ dag: 'Mån', datum: '13 aug', procent: 60 },
	{ dag: 'Tis', datum: '13 aug', procent: 40 },
	{ dag: 'Ons', datum: '13 aug', procent: 30 },
	{ dag: 'Tor', datum: '13 aug', procent: 100, idag: true },
	{ dag: 'Fre', datum: '13 aug', procent: 90 },
	{ dag: 'Lör', datum: '13 aug', procent: 80 },
	{ dag: 'Sön', datum: '13 aug', procent: 50 },
	{ dag: 'Mån', datum: '13 aug', procent: 100 },
	{ dag: 'Tis', datum: '13 aug', procent: 80 },
	{ dag: 'Ons', datum: '13 aug', procent: 50 },
	{ dag: 'Tor', datum: '13 aug', procent: 30 },
	{ dag: 'Fre', datum: '13 aug', procent: 50 },
	{ dag: 'Lör', datum: '13 aug', procent: 20 },
	{ dag: 'Sön', datum: '13 aug', procent: 50 },
];

/** Bookings shown in the weekly calendar grid (Monday=0 .. Sunday=6). */
export const bokningar: Bokning[] = [
	{ dag: 4, startTimme: 10, langdTimmar: 1, titel: 'Körlektion', larare: 'Mathijs van Wijnen', bokad: true },
	{ dag: 4, startTimme: 13, langdTimmar: 1, titel: 'Körlektion', larare: 'Jimmie Ahlberg', bokad: true },
	{ dag: 1, startTimme: 9, langdTimmar: 1, titel: 'Teorilektion', larare: 'Mathijs van Wijnen', bokad: true },
	{ dag: 2, startTimme: 11, langdTimmar: 2, titel: 'Riskettan', larare: 'Jimmie Ahlberg', bokad: true },
];

export const veckodagar = ['mån', 'tis', 'ons', 'tor', 'fre', 'lör', 'sön'];
